apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: argocd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: 05021997/my-app-image:master-40add28f0f34862984443a69f88510e63a6d5b6d
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
