apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: argocd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: 05021997/my-app-image:main-4fe43be1b61f690061d202e9c64b7e2046248436
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
